version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: github
      POSTGRES_NAME: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"

